import cv2
import numpy as np
import threading
import time
import os
import json
import argparse
import base64
import logging
from datetime import datetime
from flask import Flask, Response, abort, jsonify, send_from_directory, request
from collections import deque

# ── Logging ──────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger(__name__)
logging.getLogger('werkzeug').setLevel(logging.ERROR)

import sys

if getattr(sys, 'frozen', False):
    # Running as a PyInstaller executable
    app_base_dir = os.path.dirname(sys.executable)
    bundled_base_dir = getattr(sys, "_MEIPASS", app_base_dir)
    dist_dir = os.path.join(bundled_base_dir, 'dist')
    DETECTION_DIR = os.path.join(app_base_dir, "detections")
    MASK_DIR = os.path.join(app_base_dir, "masks")
else:
    # Running from source
    app_base_dir = os.path.dirname(__file__)
    bundled_base_dir = app_base_dir
    dist_dir = os.path.abspath(os.path.join(app_base_dir, '..', 'dist'))
    DETECTION_DIR = os.path.join(app_base_dir, "static", "detections")
    MASK_DIR = os.path.join(app_base_dir, "static", "masks")

os.makedirs(DETECTION_DIR, exist_ok=True)
os.makedirs(MASK_DIR, exist_ok=True)

# ── Load MetDetPy ML Model ────────────────────────────────────────────────────
PACKAGED_CONFIG_PATH = os.path.join(bundled_base_dir, "config.json")
METDETPY_MODEL_PATH = os.path.join(bundled_base_dir, "MetDetPy", "weights", "yolov5s_v2.onnx")
ml_net = None

def load_ml_model():
    global ml_net
    if os.path.exists(METDETPY_MODEL_PATH):
        try:
            net = cv2.dnn.readNet(METDETPY_MODEL_PATH)
            # Use OpenCV CPU backend to avoid requiring onnxruntime
            net.setPreferableBackend(cv2.dnn.DNN_BACKEND_OPENCV)
            net.setPreferableTarget(cv2.dnn.DNN_TARGET_CPU)
            log.info("MetDetPy ML Model (YOLOv5s) loaded successfully via cv2.dnn.")
            
            # Dummy forward pass to warm up
            dummy = np.zeros((640, 640, 3), dtype=np.uint8)
            blob = cv2.dnn.blobFromImage(dummy, 1/255.0, (640, 640), swapRB=True, crop=False)
            net.setInput(blob)
            net.forward()
            ml_net = net
        except Exception as e:
            ml_net = None
            log.warning(f"MetDetPy ML model disabled. The ONNX file may be missing/corrupt or unsupported by OpenCV: {e}")
    else:
        log.warning(f"MetDetPy ML Model not found at {METDETPY_MODEL_PATH}")

load_ml_model()

# Serve the 'dist' folder generated by 'npm run build'
app = Flask(__name__, static_folder=dist_dir, static_url_path='/')


RUNTIME_CONFIG = {"cameras": []}
CONFIG_FILE_PATH = "config.json"
CONFIG_LOCK = threading.Lock()
ML_LOCK = threading.Lock()

# ── Global state ─────────────────────────────────────────────────────────────
detections = deque(maxlen=1000)
frame_buffer = {}
camera_stats = {}
stats = {
    "total": 0,
    "fireballs": 0,
    "meteors": 0,
    "started": datetime.now().isoformat(),
    "fps": 0,
    "status": "stopped",
}
detection_lock = threading.Lock()

METDETPY_CLASSES = {
    0: "METEOR",
    1: "PLANE/SAT",
    2: "RED_SPRITE",
    3: "LIGHTNING",
    4: "JET",
    5: "RARE_SPRITE",
    6: "SPACECRAFT",
    7: "BUGS",
}


def resolve_default_config_path():
    local_config = os.path.join(app_base_dir, "config.local.json")
    writable_config = os.path.join(app_base_dir, "config.json")
    if os.path.exists(local_config):
        return local_config
    if getattr(sys, "frozen", False) and not os.path.exists(writable_config) and os.path.exists(PACKAGED_CONFIG_PATH):
        try:
            with open(PACKAGED_CONFIG_PATH, "r", encoding="utf-8") as f:
                write_config_atomic(writable_config, json.load(f))
        except Exception as exc:
            log.warning(f"Could not initialize writable config: {exc}")
    if os.path.exists(writable_config):
        return writable_config
    return PACKAGED_CONFIG_PATH


def write_config_atomic(path, data):
    tmp_path = f"{path}.tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    os.replace(tmp_path, path)


def validate_masks(masks):
    validated = []
    if not isinstance(masks, list):
        return validated
    for mask in masks:
        if not isinstance(mask, list) or len(mask) != 4:
            continue
        try:
            x, y, w, h = [float(v) for v in mask]
        except (TypeError, ValueError):
            continue
        x = max(0.0, min(1.0, x))
        y = max(0.0, min(1.0, y))
        w = max(0.0, min(1.0 - x, w))
        h = max(0.0, min(1.0 - y, h))
        if w > 0 and h > 0:
            validated.append([x, y, w, h])
    return validated


def safe_camera_id(cam_id):
    return "".join(ch if ch.isalnum() or ch in ("-", "_") else "_" for ch in str(cam_id)) or "camera"


def brush_mask_path(cam_id):
    return os.path.join(MASK_DIR, f"camera_{safe_camera_id(cam_id)}_mask.bmp")


def decode_mask_data_url(data_url):
    if not isinstance(data_url, str) or "," not in data_url:
        raise ValueError("Mask image must be a data URL.")
    _, encoded = data_url.split(",", 1)
    raw = base64.b64decode(encoded)
    arr = np.frombuffer(raw, dtype=np.uint8)
    image = cv2.imdecode(arr, cv2.IMREAD_UNCHANGED)
    if image is None:
        raise ValueError("Mask image could not be decoded.")
    if image.ndim == 3:
        if image.shape[2] == 4:
            image = cv2.cvtColor(image, cv2.COLOR_BGRA2GRAY)
        else:
            image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    return np.where(image >= 128, 255, 0).astype(np.uint8)


def validate_config(config):
    if not isinstance(config, dict):
        raise ValueError("Config must be a JSON object.")

    clean = dict(config)
    cameras = clean.get("cameras", [])
    if not isinstance(cameras, list):
        raise ValueError("Config cameras must be a list.")

    clean_cameras = []
    for idx, camera in enumerate(cameras):
        if not isinstance(camera, dict):
            continue
        cam_id = str(camera.get("id") or idx + 1)
        url = str(camera.get("url") or "").strip()
        if not url:
            continue
        clean_camera = dict(camera)
        clean_camera["id"] = cam_id
        clean_camera["name"] = str(camera.get("name") or f"Camera {cam_id}")
        clean_camera["url"] = url
        clean_camera["ignore_regions"] = validate_masks(camera.get("ignore_regions", []))
        clean_cameras.append(clean_camera)

    clean["cameras"] = clean_cameras
    return clean


def _derive_overall_status(statuses):
    if not statuses:
        return "stopped"
    if any(s == "running" for s in statuses):
        return "running"
    if any(s == "connecting" for s in statuses):
        return "connecting"
    if any(s == "error" for s in statuses):
        return "error"
    return "stopped"


def set_camera_state(stream_id, **updates):
    stream_id = str(stream_id)
    with detection_lock:
        state = camera_stats.setdefault(stream_id, {
            "id": stream_id,
            "name": f"Camera {stream_id}",
            "status": "stopped",
            "fps": 0,
            "last_frame": None,
            "last_error": None,
        })
        state.update(updates)

        camera_list = sorted(camera_stats.values(), key=lambda c: str(c.get("id", "")))
        stats["cameras"] = [dict(c) for c in camera_list]
        stats["status"] = _derive_overall_status([c.get("status", "stopped") for c in camera_list])
        fps_values = [float(c.get("fps", 0) or 0) for c in camera_list if c.get("status") == "running"]
        stats["fps"] = round(sum(fps_values) / len(fps_values), 1) if fps_values else 0


def snapshot_stats():
    with detection_lock:
        return dict(stats)


def redact_stream_url(url):
    if "@" not in url or "://" not in url:
        return url
    scheme, rest = url.split("://", 1)
    return f"{scheme}://***:***@{rest.split('@', 1)[1]}"


class MeteorDetector:
    def __init__(self, cfg):
        self.cfg = cfg
        self.bg_sub = cv2.createBackgroundSubtractorMOG2(
            history=self.get_cfg("bg_history", 200),
            varThreshold=self.get_cfg("bg_threshold", 50),
            detectShadows=False,
        )
        self.frame_count = 0
        self.ignore_regions = cfg.get("ignore_regions", [])
        self.brush_mask_path = cfg.get("brush_mask_path")
        self._brush_mask = None
        self._brush_mask_cache_key = None
        self.fg_mask_history = deque(maxlen=self.get_cfg("temporal_history", 10))

    def get_cfg(self, key, default_val=0):
        return RUNTIME_CONFIG.get(key, self.cfg.get(key, default_val))

    def _annotate_status(self, frame, status_text=None):
        annotated = frame.copy()
        h, w = annotated.shape[:2]
        ts = datetime.now().strftime("%Y-%m-%d  %H:%M:%S")
        cv2.putText(annotated, ts, (10, h - 12),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, (180, 180, 180), 1)
        if status_text:
            cv2.putText(annotated, status_text, (max(10, w - 420), h - 12),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 140, 255), 1)
        else:
            cv2.putText(annotated, "LIVE", (w - 48, h - 12),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 200, 80), 1)
        return annotated

    def _region_to_pixels(self, region, width, height):
        rx_pct, ry_pct, rw_pct, rh_pct = region
        if rx_pct <= 1.0 and ry_pct <= 1.0 and rw_pct <= 1.0 and rh_pct <= 1.0:
            rx = int(rx_pct * width)
            ry = int(ry_pct * height)
            rw = int(rw_pct * width)
            rh = int(rh_pct * height)
        else:
            rx, ry, rw, rh = int(rx_pct), int(ry_pct), int(rw_pct), int(rh_pct)
        rx = max(0, min(width - 1, rx))
        ry = max(0, min(height - 1, ry))
        rw = max(0, min(width - rx, rw))
        rh = max(0, min(height - ry, rh))
        return rx, ry, rw, rh

    def _mask_ignore_regions(self, width, height, *images):
        for region in self.ignore_regions:
            rx, ry, rw, rh = self._region_to_pixels(region, width, height)
            for image in images:
                cv2.rectangle(image, (rx, ry), (rx + rw, ry + rh), 0, -1)
        brush_mask = self._get_brush_mask(width, height)
        if brush_mask is not None:
            masked = brush_mask < 128
            for image in images:
                image[masked] = 0

    def _draw_ignore_regions(self, annotated):
        h, w = annotated.shape[:2]
        for region in self.ignore_regions:
            rx, ry, rw, rh = self._region_to_pixels(region, w, h)
            overlay = annotated.copy()
            cv2.rectangle(overlay, (rx, ry), (rx + rw, ry + rh), (0, 0, 80), -1)
            cv2.addWeighted(overlay, 0.3, annotated, 0.7, 0, annotated)
        brush_mask = self._get_brush_mask(w, h)
        if brush_mask is not None:
            overlay = annotated.copy()
            overlay[brush_mask < 128] = (0, 0, 110)
            cv2.addWeighted(overlay, 0.35, annotated, 0.65, 0, annotated)

    def _get_brush_mask(self, width, height):
        path = self.brush_mask_path
        if not path or not os.path.exists(path):
            self._brush_mask = None
            self._brush_mask_cache_key = None
            return None
        try:
            stat = os.stat(path)
            cache_key = (path, stat.st_mtime_ns, width, height)
            if cache_key == self._brush_mask_cache_key:
                return self._brush_mask
            mask = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
            if mask is None:
                return None
            if mask.shape[:2] != (height, width):
                mask = cv2.resize(mask, (width, height), interpolation=cv2.INTER_NEAREST)
            self._brush_mask = np.where(mask >= 128, 255, 0).astype(np.uint8)
            self._brush_mask_cache_key = cache_key
            return self._brush_mask
        except Exception as exc:
            log.warning(f"Could not load brush mask {path}: {exc}")
            self._brush_mask = None
            self._brush_mask_cache_key = None
            return None

    def _sample_line_points(self, x1, y1, x2, y2, n):
        return [(int(x1 + t*(x2-x1)/n), int(y1 + t*(y2-y1)/n)) for t in range(n+1)]

    def _line_quality(self, gray, x1, y1, x2, y2):
        h, w = gray.shape[:2]
        length = max(1.0, float(np.hypot(x2 - x1, y2 - y1)))
        nx = -(y2 - y1) / length
        ny = (x2 - x1) / length
        offset = int(self.get_cfg("line_side_sample_offset", 6))
        pts = self._sample_line_points(x1, y1, x2, y2, 24)

        line_vals = []
        side_vals = []
        for px, py in pts:
            px = max(0, min(w - 1, px))
            py = max(0, min(h - 1, py))
            line_vals.append(int(gray[py, px]))
            for sign in (-1, 1):
                sx = max(0, min(w - 1, int(px + sign * nx * offset)))
                sy = max(0, min(h - 1, int(py + sign * ny * offset)))
                side_vals.append(int(gray[sy, sx]))

        line_mean = float(np.mean(line_vals)) if line_vals else 0.0
        side_mean = float(np.mean(side_vals)) if side_vals else 0.0
        return line_mean, line_mean - side_mean

    def _event_bbox(self, event, frame_width, frame_height, pad=18):
        if event["type"] == "fireball":
            x, y, w, h = event["bbox"]
            return x, y, x + w, y + h

        x1, y1, x2, y2 = event["line"]
        left = max(0, min(x1, x2) - pad)
        top = max(0, min(y1, y2) - pad)
        right = min(frame_width - 1, max(x1, x2) + pad)
        bottom = min(frame_height - 1, max(y1, y2) + pad)
        return left, top, right, bottom

    def _bbox_iou(self, a, b):
        ax1, ay1, ax2, ay2 = a
        bx1, by1, bx2, by2 = b
        ix1, iy1 = max(ax1, bx1), max(ay1, by1)
        ix2, iy2 = min(ax2, bx2), min(ay2, by2)
        iw, ih = max(0, ix2 - ix1), max(0, iy2 - iy1)
        inter = iw * ih
        if inter == 0:
            return 0.0
        area_a = max(1, (ax2 - ax1) * (ay2 - ay1))
        area_b = max(1, (bx2 - bx1) * (by2 - by1))
        return inter / float(area_a + area_b - inter)

    def _detect_ml_candidates(self, frame):
        if ml_net is None:
            return []

        h, w = frame.shape[:2]
        try:
            blob = cv2.dnn.blobFromImage(frame, 1/255.0, (640, 640), swapRB=True, crop=False)
            with ML_LOCK:
                ml_net.setInput(blob)
                outputs = ml_net.forward()
        except Exception as exc:
            log.warning(f"MetDetPy verification skipped: {exc}")
            return []

        preds = outputs[0] if isinstance(outputs, (list, tuple)) else outputs
        if preds.ndim == 3:
            preds = preds[0]

        x_scale = w / 640.0
        y_scale = h / 640.0
        boxes = []
        scores = []
        candidates = []
        min_conf = float(self.get_cfg("ml_min_confidence", 0.18))

        for row in preds:
            obj_conf = float(row[4])
            if obj_conf <= 0.01:
                continue
            class_scores = row[5:]
            if len(class_scores) == 0:
                continue
            class_id = int(np.argmax(class_scores))
            conf = obj_conf * float(class_scores[class_id])
            if conf < min_conf:
                continue
            cx, cy, bw, bh = [float(v) for v in row[:4]]
            x1 = int((cx - bw / 2) * x_scale)
            y1 = int((cy - bh / 2) * y_scale)
            x2 = int((cx + bw / 2) * x_scale)
            y2 = int((cy + bh / 2) * y_scale)
            x1 = max(0, min(w - 1, x1))
            y1 = max(0, min(h - 1, y1))
            x2 = max(0, min(w - 1, x2))
            y2 = max(0, min(h - 1, y2))
            if x2 <= x1 or y2 <= y1:
                continue
            boxes.append([x1, y1, x2 - x1, y2 - y1])
            scores.append(conf)
            candidates.append({
                "class_id": class_id,
                "class_name": METDETPY_CLASSES.get(class_id, "UNKNOWN"),
                "conf": conf,
                "bbox": (x1, y1, x2, y2),
            })

        if not candidates:
            return []

        keep = cv2.dnn.NMSBoxes(boxes, scores, min_conf, float(self.get_cfg("ml_nms_threshold", 0.35)))
        if len(keep) == 0:
            return []
        keep = np.array(keep).reshape(-1).tolist()
        return [candidates[i] for i in keep]

    def _ml_decision(self, event, ml_candidates, frame_width, frame_height):
        if not ml_candidates:
            if self.get_cfg("require_ml_confirmation", False):
                return False, None
            return True, None

        event_box = self._event_bbox(event, frame_width, frame_height)
        min_iou = float(self.get_cfg("ml_overlap_iou", 0.03))
        matches = [
            c for c in ml_candidates
            if self._bbox_iou(event_box, c["bbox"]) >= min_iou
        ]
        if not matches:
            if self.get_cfg("require_ml_confirmation", False):
                return False, None
            return True, None

        best = max(matches, key=lambda c: c["conf"])
        reject_classes = set(self.get_cfg("ml_reject_classes", [1, 3, 7]))
        if best["class_id"] in reject_classes:
            event["reject_reason"] = f"ML {best['class_name']} {best['conf']:.2f}"
            return False, best

        event["ml_class"] = best["class_name"]
        event["ml_conf"] = float(best["conf"])
        return True, best

    def process(self, frame):
        self.frame_count += 1
        events = []
        if frame is None:
            return None, []
        h, w = frame.shape[:2]

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        warmup_frames = int(self.get_cfg("warmup_frames", 90))
        if self.frame_count <= warmup_frames:
            self.bg_sub.apply(gray, learningRate=float(self.get_cfg("warmup_learning_rate", 0.08)))
            return self._annotate_status(frame, f"WARMING UP {self.frame_count}/{warmup_frames}"), []
        
        avg_brightness = np.mean(gray)
        current_max_b = self.get_cfg("max_overall_brightness", 80)
        if avg_brightness > current_max_b:
            # Too bright (daylight or full moon), skip detection
            self.bg_sub.apply(gray, learningRate=float(self.get_cfg("standby_learning_rate", 0.02)))
            return self._annotate_status(frame, f"STANDBY - TOO BRIGHT (b={int(avg_brightness)})"), []

        gray = cv2.GaussianBlur(gray, (3, 3), 0)

        fg_mask = self.bg_sub.apply(gray)
        kernel = np.ones((2, 2), np.uint8)
        fg_mask = cv2.morphologyEx(fg_mask, cv2.MORPH_OPEN, kernel)
        fg_mask = cv2.morphologyEx(fg_mask, cv2.MORPH_DILATE, kernel)
        
        self.fg_mask_history.append(fg_mask)
        combined_fg = np.zeros_like(fg_mask)
        for fm in self.fg_mask_history:
            combined_fg = cv2.bitwise_or(combined_fg, fm)

        self._mask_ignore_regions(w, h, combined_fg, gray, fg_mask)

        motion_ratio = cv2.countNonZero(combined_fg) / float(w * h)
        if motion_ratio > float(self.get_cfg("max_motion_ratio", 0.14)):
            return self._annotate_status(frame, f"STANDBY - CLOUD/MOTION ({motion_ratio:.0%})"), []

        motion_contours, _ = cv2.findContours(combined_fg, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        max_motion_area = max((cv2.contourArea(c) for c in motion_contours), default=0)
        if max_motion_area / float(w * h) > float(self.get_cfg("max_motion_blob_ratio", 0.18)):
            return self._annotate_status(frame, "STANDBY - LARGE MOVING AREA"), []

        _, bright = cv2.threshold(gray, self.get_cfg("fireball_threshold", 220), 255, cv2.THRESH_BINARY)
        bright_masked = cv2.bitwise_and(bright, fg_mask)
        bright_contours, _ = cv2.findContours(bright_masked, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        bg_img = self.bg_sub.getBackgroundImage()
        bg_gray = None
        if bg_img is not None:
            if len(bg_img.shape) == 3:
                bg_gray = cv2.cvtColor(bg_img, cv2.COLOR_BGR2GRAY)
            else:
                bg_gray = bg_img

        for cnt in bright_contours:
            area = cv2.contourArea(cnt)
            if area > self.get_cfg("fireball_min_area", 80):
                # Ignore excessively large flashes (e.g., lightning or whole sky blooming) unless configured otherwise
                if area > self.get_cfg("fireball_max_area", 25000):
                    continue
                
                x, y, cw, ch = cv2.boundingRect(cnt)
                if cw / float(w) > float(self.get_cfg("fireball_max_width_ratio", 0.22)):
                    continue
                if ch / float(h) > float(self.get_cfg("fireball_max_height_ratio", 0.22)):
                    continue
                fill_ratio = area / float(max(1, cw * ch))
                if fill_ratio < float(self.get_cfg("fireball_min_fill_ratio", 0.08)):
                    continue
                
                # Filter out objects that are already bright in the background model (like the Moon)
                # If they are persistently bright, it's not a fireball.
                if bg_gray is not None:
                    bg_roi = bg_gray[y:y+ch, x:x+cw]
                    if bg_roi.size > 0 and np.max(bg_roi) > self.get_cfg("fireball_threshold", 220) - 40:
                        continue
                        
                brightness = np.max(gray[y:y+ch, x:x+cw])
                roi = gray[y:y+ch, x:x+cw]
                local_contrast = int(np.max(roi) - np.median(roi)) if roi.size else 0
                if local_contrast < int(self.get_cfg("fireball_min_local_contrast", 35)):
                    continue
                events.append({
                    "type": "fireball",
                    "bbox": (x, y, cw, ch),
                    "brightness": int(brightness),
                    "area": int(area),
                })

        if not events:
            lines = cv2.HoughLinesP(
                combined_fg,
                rho=1,
                theta=np.pi / 180,
                threshold=self.get_cfg("hough_threshold", 25),
                minLineLength=self.get_cfg("min_streak_length", 40),
                maxLineGap=self.get_cfg("max_line_gap", 8),
            )
            if lines is not None:
                for line in lines:
                    x1, y1, x2, y2 = line[0]
                    
                    # Check if line intersects any ignore region
                    in_mask = False
                    for rx_pct, ry_pct, rw_pct, rh_pct in self.ignore_regions:
                        if rx_pct <= 1.0 and ry_pct <= 1.0 and rw_pct <= 1.0 and rh_pct <= 1.0:
                            rx = int(rx_pct * w)
                            ry = int(ry_pct * h)
                            rw = int(rw_pct * w)
                            rh = int(rh_pct * h)
                        else:
                            rx, ry, rw, rh = int(rx_pct), int(ry_pct), int(rw_pct), int(rh_pct)
                        # Check endpoint 1
                        if rx <= x1 <= rx+rw and ry <= y1 <= ry+rh:
                            in_mask = True
                            break
                        # Check endpoint 2
                        if rx <= x2 <= rx+rw and ry <= y2 <= ry+rh:
                            in_mask = True
                            break
                    if in_mask:
                        continue

                    length = np.hypot(x2 - x1, y2 - y1)
                    if length < self.get_cfg("min_streak_length", 40):
                        continue
                    if length > self.get_cfg("max_streak_length_ratio", 0.58) * np.hypot(w, h):
                        continue
                    edge_margin = int(self.get_cfg("edge_margin_px", 8))
                    touches_left = x1 <= edge_margin or x2 <= edge_margin
                    touches_right = x1 >= w - edge_margin or x2 >= w - edge_margin
                    touches_top = y1 <= edge_margin or y2 <= edge_margin
                    touches_bottom = y1 >= h - edge_margin or y2 >= h - edge_margin
                    if (touches_left and touches_right) or (touches_top and touches_bottom):
                        continue
                    angle = abs(np.degrees(np.arctan2(y2 - y1, x2 - x1)))
                    if angle < self.get_cfg("min_angle", 10) or angle > self.get_cfg("max_angle", 170):
                        continue
                    avg_b, contrast = self._line_quality(gray, x1, y1, x2, y2)
                    if avg_b < self.get_cfg("min_streak_brightness", 60):
                        continue
                    if contrast < self.get_cfg("min_line_contrast", 12):
                        continue
                    events.append({
                        "type": "meteor",
                        "line": (x1, y1, x2, y2),
                        "length": float(length),
                        "brightness": int(avg_b),
                        "contrast": float(contrast),
                        "angle": float(angle),
                    })
                    break

        annotated = frame.copy()
        self._draw_ignore_regions(annotated)

        ml_candidates = self._detect_ml_candidates(frame) if events else []
        accepted_events = []
        for ev in events:
            accepted, match = self._ml_decision(ev, ml_candidates, w, h)
            if not accepted:
                log.info(f"Rejected candidate on ML/filter: {ev.get('reject_reason', ev['type'])}")
                continue
            if match:
                ev["ml_label"] = f"[ML] {match['class_name']} {match['conf']:.2f}"
            accepted_events.append(ev)
        events = accepted_events

        for ev in events:
            if ev["type"] == "fireball":
                x, y, cw, ch = ev["bbox"]
                cv2.rectangle(annotated, (x, y), (x+cw, y+ch), (0, 100, 255), 2)
                label = ev.get("ml_label", f"FIREBALL b={ev['brightness']}")
                cv2.putText(annotated, label, (x, y - 8),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 100, 255), 2)
            elif ev["type"] == "meteor":
                bx, by, bx2, by2 = self._event_bbox(ev, w, h, pad=15)
                final_conf = min(0.99, 0.70 + (ev['brightness']/255.0) * 0.20 + min(ev['length']/300.0, 0.09))
                label_text = ev.get("ml_label", f"METEOR: {final_conf:.2f}")
                box_color = (0, 255, 50)
                cv2.rectangle(annotated, (bx, by), (bx2, by2), box_color, 1)
                cv2.putText(annotated, label_text, (bx, by - 8),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.45, box_color, 1)

        ts = datetime.now().strftime("%Y-%m-%d  %H:%M:%S")
        cv2.putText(annotated, ts, (10, h - 12),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, (180, 180, 180), 1)
        cv2.putText(annotated, "LIVE", (w - 48, h - 12),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 200, 80), 1)

        return annotated, events

def stream_worker(stream_id, cam_info, global_cfg):
    # Merge global cfg with camera specific settings
    cfg = global_cfg.copy()
    cfg["ignore_regions"] = []
    cfg["brush_mask_path"] = cam_info.get("brush_mask_path") or brush_mask_path(stream_id)
    rtsp_url = cam_info["url"]
    camera_name = cam_info.get("name", f"Camera {stream_id}")
    set_camera_state(stream_id, name=camera_name, status="connecting", fps=0)
    
    detector = MeteorDetector(cfg)
    fps_counter = 0
    fps_timer = time.time()
    last_detect_time = 0

    while True:
        set_camera_state(stream_id, status="connecting", fps=0, last_error=None)
        log.info(f"Connecting to Camera {stream_id} -> {redact_stream_url(rtsp_url)}")
        cap = cv2.VideoCapture(rtsp_url, cv2.CAP_FFMPEG)
        if hasattr(cv2, 'CAP_PROP_BUFFERSIZE'):
            cap.set(cv2.CAP_PROP_BUFFERSIZE, 2)

        if not cap.isOpened():
            log.error(f"Cannot open stream {stream_id}, retrying in 10s…")
            set_camera_state(stream_id, status="error", fps=0, last_error="Cannot open stream")
            time.sleep(10)
            continue

        set_camera_state(stream_id, status="running", fps=0)
        log.info(f"Stream {stream_id} opened ✓")

        while True:
            ret, frame = cap.read()
            if not ret:
                log.warning(f"Frame read failed for setup {stream_id}, reconnecting…")
                set_camera_state(stream_id, status="connecting", fps=0, last_error="Frame read failed")
                break

            resize_width = int(RUNTIME_CONFIG.get("resize_width", cfg.get("resize_width", 1280)) or 0)
            if resize_width and frame.shape[1] != resize_width:
                scale = resize_width / frame.shape[1]
                frame = cv2.resize(frame, (resize_width, int(frame.shape[0] * scale)))

            # Update ignore regions dynamically
            for c in RUNTIME_CONFIG.get("cameras", []):
                if str(c["id"]) == str(stream_id):
                    detector.ignore_regions = []
                    detector.brush_mask_path = c.get("brush_mask_path") or brush_mask_path(stream_id)
                    break

            annotated, events = detector.process(frame)

            if events and (time.time() - last_detect_time > cfg.get("cooldown_seconds", 1.5)):
                last_detect_time = time.time()
                ts = datetime.now()
                fname = f"cam{stream_id}_" + ts.strftime("%Y%m%d_%H%M%S_%f") + ".jpg"
                fpath = os.path.join(DETECTION_DIR, fname)
                cv2.imwrite(fpath, annotated, [cv2.IMWRITE_JPEG_QUALITY, 92])

                for ev in events:
                    record = {
                        "id": fname,
                        "time": ts.isoformat(),
                        "type": ev["type"],
                        "brightness": ev.get("brightness", 0),
                        "length": ev.get("length", 0),
                        "image": fname,
                        "camera": stream_id
                    }
                    with detection_lock:
                        detections.appendleft(record)
                        stats["total"] += 1
                        stats[ev["type"] + "s"] += 1

                log.info(f"Detection on Cam {stream_id}: {[e['type'] for e in events]}")

            _, buf = cv2.imencode(".jpg", annotated, [cv2.IMWRITE_JPEG_QUALITY, 75])
            frame_buffer[str(stream_id)] = buf.tobytes()
            set_camera_state(stream_id, last_frame=datetime.now().isoformat())

            fps_counter += 1
            if time.time() - fps_timer >= 2:
                set_camera_state(stream_id, status="running", fps=round(fps_counter / (time.time() - fps_timer), 1))
                fps_counter = 0
                fps_timer = time.time()

        cap.release()
        time.sleep(3)

# ── Flask Routes ──────────────────────────────────────────────────────────────
def serve_spa_index():
    index_path = os.path.join(dist_dir, "index.html")
    if os.path.exists(index_path):
        return app.send_static_file("index.html")
    return (
        "<h1>TAPO Meteor Network</h1>"
        "<p>Frontend build missing. Run <code>npm install</code> and "
        "<code>npm run build</code> in the project root, then restart the app.</p>",
        503,
    )

@app.route("/")
def index():
    return serve_spa_index()

@app.route("/video_feed/<stream_id>")
def video_feed(stream_id):
    def gen():
        while True:
            frame = frame_buffer.get(str(stream_id))
            if frame:
                yield (b"--frame\r\n"
                       b"Content-Type: image/jpeg\r\n\r\n" + frame + b"\r\n")
            time.sleep(0.04) 
    return Response(gen(), mimetype="multipart/x-mixed-replace; boundary=frame")

@app.route("/api/detections")
def api_detections():
    with detection_lock:
        return jsonify(list(detections)[:500])

@app.route("/api/detections/<id>", methods=["DELETE"])
def api_delete_detection(id):
    if os.path.basename(id) != id or "/" in id or "\\" in id or not id.lower().endswith(".jpg"):
        abort(400)

    with detection_lock:
        existing = next((d for d in detections if d["id"] == id), None)
        if existing is None:
            abort(404)

        new_dets = [d for d in detections if d["id"] != id]
        detections.clear()
        detections.extend(new_dets)

    detection_dir_abs = os.path.abspath(DETECTION_DIR)
    fpath = os.path.abspath(os.path.join(detection_dir_abs, id))
    if os.path.commonpath([detection_dir_abs, fpath]) != detection_dir_abs:
        abort(400)
    if os.path.exists(fpath):
        try:
            os.remove(fpath)
        except Exception as e:
            log.error(f"Failed to delete {fpath}: {e}")
                
    return jsonify({"status": "ok"})

@app.route("/api/stats")
def api_stats():
    return jsonify(snapshot_stats())

@app.route("/api/config", methods=["GET", "POST"])
def api_config():
    global RUNTIME_CONFIG
    if request.method == "POST":
        try:
            new_config = validate_config(request.get_json(silent=True))
            with CONFIG_LOCK:
                RUNTIME_CONFIG = new_config
                write_config_atomic(CONFIG_FILE_PATH, RUNTIME_CONFIG)
            return jsonify({"status": "ok"})
        except Exception as e:
            log.error(f"Failed to save config: {e}")
            return jsonify({"status": "error", "message": str(e)}), 500
    with CONFIG_LOCK:
        return jsonify(RUNTIME_CONFIG)

@app.route("/api/config/masks/<cam_id>", methods=["POST"])
def api_set_masks(cam_id):
    try:
        payload = request.get_json(silent=True) or {}
        masks = validate_masks(payload.get("masks", []))
        updated = False
        with CONFIG_LOCK:
            for c in RUNTIME_CONFIG.get("cameras", []):
                if str(c["id"]) == str(cam_id):
                    c["ignore_regions"] = masks
                    updated = True
                    break
            if not updated:
                return jsonify({"status": "error", "message": "Camera not found"}), 404
            write_config_atomic(CONFIG_FILE_PATH, RUNTIME_CONFIG)
            
        return jsonify({"status": "ok"})
    except Exception as e:
        log.error(f"Failed to update masks: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route("/api/brush-mask/<cam_id>", methods=["GET", "POST", "DELETE"])
def api_brush_mask(cam_id):
    path = brush_mask_path(cam_id)
    if request.method == "GET":
        if not os.path.exists(path):
            abort(404)
        mask = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        if mask is None:
            abort(404)
        ok, png = cv2.imencode(".png", mask)
        if not ok:
            abort(500)
        return Response(png.tobytes(), mimetype="image/png")

    if request.method == "DELETE":
        if os.path.exists(path):
            os.remove(path)
        return jsonify({"status": "ok"})

    try:
        payload = request.get_json(silent=True) or {}
        mask = decode_mask_data_url(payload.get("mask"))
        if mask.size == 0:
            raise ValueError("Mask image is empty.")
        cv2.imwrite(path, mask)
        return jsonify({
            "status": "ok",
            "path": path,
            "width": int(mask.shape[1]),
            "height": int(mask.shape[0]),
        })
    except Exception as e:
        log.error(f"Failed to save brush mask for camera {cam_id}: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route("/static/detections/<path:filename>")
def serve_detection(filename):
    if os.path.basename(filename) != filename or "/" in filename or "\\" in filename:
        abort(400)
    return send_from_directory(DETECTION_DIR, filename)

@app.errorhandler(404)
def not_found(e):
    return serve_spa_index()

DEFAULT_CFG = {
    "bg_history": 200,
    "bg_threshold": 50,
    "fireball_threshold": 220,
    "fireball_min_area": 80,
    "fireball_max_area": 25000,
    "fireball_max_width_ratio": 0.22,
    "fireball_max_height_ratio": 0.22,
    "fireball_min_fill_ratio": 0.08,
    "fireball_min_local_contrast": 35,
    "hough_threshold": 25,
    "min_streak_length": 40,
    "max_streak_length_ratio": 0.58,
    "max_line_gap": 8,
    "min_angle": 12,
    "max_angle": 168,
    "min_streak_brightness": 60,
    "min_line_contrast": 12,
    "max_overall_brightness": 80,
    "max_motion_ratio": 0.14,
    "max_motion_blob_ratio": 0.18,
    "temporal_history": 4,
    "warmup_frames": 90,
    "warmup_learning_rate": 0.08,
    "standby_learning_rate": 0.02,
    "ml_min_confidence": 0.18,
    "ml_nms_threshold": 0.35,
    "ml_overlap_iou": 0.03,
    "ml_reject_classes": [1, 3, 7],
    "require_ml_confirmation": False,
    "cooldown_seconds": 2.5,
    "resize_width": 1280,
}

import webbrowser

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Multi-Camera Meteor Detector")
    parser.add_argument("--config", default=None, help="Path to JSON config with RTSP urls")
    parser.add_argument("--port", default=5000, type=int)
    parser.add_argument("--host", default="127.0.0.1")
    args = parser.parse_args()

    if args.config is None:
        CONFIG_FILE_PATH = resolve_default_config_path()
    elif getattr(sys, 'frozen', False):
        exe_dir = os.path.dirname(sys.executable)
        CONFIG_FILE_PATH = os.path.join(exe_dir, args.config) if not os.path.isabs(args.config) else args.config
    else:
        CONFIG_FILE_PATH = args.config if os.path.isabs(args.config) else os.path.abspath(os.path.join(app_base_dir, args.config))

    # Load cameras from config
    if os.path.exists(CONFIG_FILE_PATH):
        with open(CONFIG_FILE_PATH, 'r', encoding="utf-8") as f:
            RUNTIME_CONFIG.update(validate_config(json.load(f)))
    
    cameras = RUNTIME_CONFIG.get("cameras", [])
    if not cameras:
        # Fallback to test/dummy 
        print("Warning: No cameras found in config.json. Please configure your RTSP streams.")
        cameras = [{"id": "1", "name": "Camera 1", "url": "rtsp://username:password@192.168.1.100:554/stream1"}]
        RUNTIME_CONFIG["cameras"] = cameras

    # Start a thread for each camera
    for cam in cameras:
        frame_buffer[str(cam["id"])] = None
        set_camera_state(cam["id"], name=cam.get("name", f"Camera {cam['id']}"), status="stopped", fps=0)
        t = threading.Thread(target=stream_worker, args=(cam["id"], cam, DEFAULT_CFG), daemon=True)
        t.start()
        
    dist_path = dist_dir
    if not getattr(sys, 'frozen', False) and not os.path.exists(dist_path):
        log.error("=========================================================")
        log.error("ERROR: 'dist' folder not found!")
        log.error("You must build the UI first. Open a terminal in the root")
        log.error("folder and run: npm install && npm run build")
        log.error("=========================================================")

    log.info(f"Starting Local Server on http://localhost:{args.port}")
    
    # Auto-open browser
    def open_browser():
        time.sleep(1.5)
        webbrowser.open(f"http://localhost:{args.port}")
    
    threading.Thread(target=open_browser, daemon=True).start()

    app.run(host=args.host, port=args.port, threaded=True, debug=False)
